version: "3.9"
services:
  web_app:
    container_name: "django_app"
    build: .
    ports:
      - 8000:8000
    volumes:
      - django_app_volume:/data
  my_db:
    container_name: "django_db"
    image: mysql:5.7
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: "test@123"
volumes:
    django_app_volume:
